# Generated by Django 3.1.7 on 2021-04-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210403_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(default=None, help_text='YYYY-MM-DD', null=True),
        ),
    ]
