# Generated by Django 3.1.7 on 2021-03-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_name', models.AutoField(primary_key=True, serialize=False)),
                ('from_user', models.CharField(max_length=255)),
                ('to_user', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_string', models.CharField(max_length=255)),
                ('message_status', models.CharField(choices=[('chat_msg', 'Chat Message'), ('chat_file', 'Chat File'), ('chat_signal', 'Chat Signal')], max_length=12)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('sent_time', models.DateTimeField()),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
            options={
                'ordering': ['sent_time'],
            },
        ),
    ]
