# Generated by Django 3.1.7 on 2021-03-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210318_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sent_by',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_status',
            field=models.CharField(choices=[('msg', 'Chat_Message'), ('err', 'Chat_Error'), ('spc', 'Chat_Special')], default='msg', max_length=3),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_string',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
