# Generated by Django 3.1.7 on 2021-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210319_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='from_user_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='to_user_online',
            field=models.BooleanField(default=False),
        ),
    ]
