# Generated by Django 3.1.7 on 2021-04-14 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210414_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='from_user_online',
            new_name='from_user_status',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='to_user_online',
            new_name='to_user_status',
        ),
    ]
